### ISSUE TITLE
qb feature: Add a 'Clone' method to all query builder types

### ISSUE THREAD

**Issue by jgiles** [scylladb/gocqlx#23]
Because query builders are mutable, they can be tricky to re-use safely.

It would be useful to be able to define some common 'base' query builder, and re-use it multiple times to build derivative queries.

You can sort of accomplish this now by defining a function to assemble the base builder and calling it repeatedly, but it would be more natural+convenient (and probably performant) to be able to keep a base builder in a variable and clone it for use in constructing variants.

**Comment by mmatczuk** [comment]
I'm not sure if it's really needed. If you have common root for multiple statements maybe it's better to have a decorator or a function that would return a prepared builder. If you need to clone it anyway there is a bunch of things you could try i.e. github.com/mitchellh/copystructure.

**Comment by jgiles** [comment]
You can't use copystructure or other copy/clone utilities because the qb structs have unexported fields.
The decorator function approach works, but adds code complexity overhead for clients.
A common pattern we have is to initialize a bunch of package variables to built CQL for re-use in serving traffic. It's always a bit annoying to define functions just for use in the package init phase.

**Comment by mmatczuk** [comment]
While I agree that prototype is a classical design pattern I find the investment not worthwhile.

A copy constructor or a clone method still requires allocations pretty much the same way that creating a new object does. So there is no win on that front. As a drawback this approach makes the code more fragile. A future patch can break the cloning so that in some cases you would get "almost cloned" version leading to nasty bugs.

> A common pattern we have is to initialize a bunch of package variables to built CQL for re-use in serving traffic.

What I'd recommend it to have a package function that would read the package variables and return a prepared builder, it's much safer.
