### ISSUE TITLE
fix using timeout order in delete stmt

### ISSUE THREAD

**Issue by AdamStawarz** [scylladb/gocqlx#246]
Looking at the DELETE statement specification [here](https://docs.scylladb.com/getting-started/dml/#select-statement),
it seems the USING clause should be at the end of the statement.

this needs to be reviewed fully https://github.com/scylladb/gocqlx/commit/979397bc5ea0e5b37559b33ef02b7e1e144d0b50
because last PR covered only SELECT stmt here: https://github.com/scylladb/gocqlx/pull/229/files

Problematic part: https://github.com/scylladb/gocqlx/blob/fc92258512d39bff365cae10d452a63cc1afc932/qb/delete.go#L36

but we have to check also all other statements

**Comment by AdamStawarz** [comment]
@yaronkaikov @avelanarius

**Comment by yaronkaikov** [comment]
@AdamStawarz could it be that you tagged me by mistake ?🤔

**Comment by AdamStawarz** [comment]
yes @yaronkaikov , sorry to bother you :)

**Comment by tarzanek** [comment]
FYI per original patch https://github.com/scylladb/gocqlx/commit/979397bc5ea0e5b37559b33ef02b7e1e144d0b50

delete and updates need similar patch as select

and please review batch, too

(insert and select look ok, others not really and need a fix)

**Comment by Gor027** [comment]
@AdamStawarz In fact, the specification you mentioned states that the `USING` clause for Delete statements should precede the `WHERE` clause. The implementation seems correct for Delete as well as Update and Batch statements. 
The problem relies on the enterprise version of ScyllaDB that Sharechat uses, @avelanarius has found it [here](https://github.com/scylladb/scylla-enterprise/issues/2564).
This enterprise version is based on the open-source version 4.3, which should not support per-query timeouts for select/insert and for delete statements, as per-query timeouts support for select/insert was meant to be available since the open-source 4.4 version ([see here](https://github.com/scylladb/scylladb/issues/7777)) and for delete statements since 4.7 ([see here](https://github.com/scylladb/scylladb/issues/8855)). However, in accordance with the request of one of the clients, the per-query timeouts support for select/insert statements was backported to an earlier enterprise version ([see here](https://github.com/scylladb/scylla-enterprise/issues/1600)), thus the newer version includes the feature for insert/select queries but does not support it for delete queries.

**Comment by Gor027** [comment]
I guess the issue does not imply a change in the driver, now, so we can close it.

**Comment by Gor027** [comment]
@AdamStawarz In fact, the specification you mentioned states that the `USING` clause for Delete statements should precede the `WHERE` clause. The implementation seems correct for Delete as well as Update and Batch statements. The problem relies on the ScyllaDB enterprise version 2021.1.15.
This enterprise version is based on the open-source version 4.3, which should not support per-query timeouts for select/insert and for delete statements, as per-query timeouts support for select/insert was meant to be available since the open-source 4.4 version ([see here](https://github.com/scylladb/scylladb/issues/7777)) and for delete statements since 4.7 ([see here](https://github.com/scylladb/scylladb/issues/8855)). However, in accordance with the request of one of the clients, the per-query timeouts support for select/insert statements was backported to an earlier enterprise version ([see here](https://github.com/scylladb/scylla-enterprise/issues/1600)), thus the newer version includes the feature for insert/select queries but does not support it for delete queries.

**Comment by Gor027** [comment]
I guess the issue does not imply a change in the driver, now, so we can close it.
